import type { Modalidade } from '../cursos/types'
import type { Universidade } from './types'

// Mock da listagem de Universidades (tela /universidades)

export type NotaMec = 1 | 2 | 3 | 4 | 5

export interface UniversidadeListagem extends Universidade {
  notaMec: NotaMec
  modalidades: Modalidade[]
}

export const universidadesListagemMock: UniversidadeListagem[] = [
  {
    id: 'u-unicesumar',
    nome: 'UniCesumar',
    sigla: null,
    tipo: 'privada',
    cidade: 'Maringá',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 214,
    notaMec: 4,
    modalidades: ['presencial', 'ead'],
  },
  {
    id: 'u-uniasselvi',
    nome: 'Uniasselvi',
    sigla: null,
    tipo: 'privada',
    cidade: 'Curitiba',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 178,
    notaMec: 4,
    modalidades: ['semipresencial', 'ead'],
  },
  {
    id: 'u-uem',
    nome: 'Universidade Estadual de Maringá',
    sigla: 'UEM',
    tipo: 'publica',
    cidade: 'Maringá',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 63,
    notaMec: 5,
    modalidades: ['presencial'],
  },
  {
    id: 'u-utfpr',
    nome: 'Universidade Tecnológica Federal do Paraná',
    sigla: 'UTFPR',
    tipo: 'publica',
    cidade: 'Londrina',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 41,
    notaMec: 5,
    modalidades: ['presencial'],
  },
  {
    id: 'u-pucpr',
    nome: 'Pontifícia Universidade Católica do Paraná',
    sigla: 'PUCPR',
    tipo: 'privada',
    cidade: 'Curitiba',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 96,
    notaMec: 5,
    modalidades: ['presencial', 'ead'],
  },
  {
    id: 'u-uel',
    nome: 'Universidade Estadual de Londrina',
    sigla: 'UEL',
    tipo: 'publica',
    cidade: 'Londrina',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 58,
    notaMec: 4,
    modalidades: ['presencial'],
  },
  {
    id: 'u-unifil',
    nome: 'Centro Universitário Filadélfia',
    sigla: 'UniFil',
    tipo: 'privada',
    cidade: 'Londrina',
    uf: 'PR',
    logoUrl: null,
    totalCursos: 37,
    notaMec: 3,
    modalidades: ['presencial', 'semipresencial'],
  },
  {
    id: 'u-usp',
    nome: 'Universidade de São Paulo',
    sigla: 'USP',
    tipo: 'publica',
    cidade: 'São Paulo',
    uf: 'SP',
    logoUrl: null,
    totalCursos: 249,
    notaMec: 5,
    modalidades: ['presencial'],
  },
  {
    id: 'u-ufsc',
    nome: 'Universidade Federal de Santa Catarina',
    sigla: 'UFSC',
    tipo: 'publica',
    cidade: 'Florianópolis',
    uf: 'SC',
    logoUrl: null,
    totalCursos: 120,
    notaMec: 5,
    modalidades: ['presencial', 'ead'],
  },
  {
    id: 'u-unisul',
    nome: 'Universidade do Sul de Santa Catarina',
    sigla: 'Unisul',
    tipo: 'privada',
    cidade: 'Tubarão',
    uf: 'SC',
    logoUrl: null,
    totalCursos: 88,
    notaMec: 3,
    modalidades: ['presencial', 'semipresencial', 'ead'],
  },
]
export const favoritosIniciaisMock = ['u-unicesumar', 'u-uniasselvi']
